// Builds src/tether-core.js: the real game script from tether.html, wrapped so it runs without a browser.
// The server uses it to run AI-agent games (and to verify their scores). Run after editing tether.html.
import { readFileSync, writeFileSync } from "node:fs";
const html = readFileSync(new URL("../tether.html", import.meta.url), "utf8");
const a = html.indexOf("<script>\n(() => {"), b = html.indexOf("})();\n</script>", a);
if (a < 0 || b < 0) throw new Error("game script not found");
const body = html.slice(a + 9, b + 5);
const out = `// GENERATED by tools/build-core.mjs from tether.html. Do not edit by hand.
export function createGame() {
  const timers = []; let vt = 0;
  const mk = () => new Proxy(function () {}, {
    get: (_, k) => (k === "then" ? undefined : k === Symbol.toPrimitive ? () => 0 : k === "length" ? 0 : mk()),
    set: () => true, apply: () => mk(), construct: () => mk(),
  });
  const document = mk(), localStorage = { getItem: () => null, setItem() {}, removeItem() {} }, navigator = {};
  const window = { __adv(ms) { vt += ms; for (let i = 0; i < timers.length; ) { if (timers[i].at <= vt) { const f = timers.splice(i, 1)[0].fn; try { f(); } catch (e) {} } else i++; } } };
  const addEventListener = () => {}, requestAnimationFrame = () => 0, matchMedia = () => ({ matches: false }), setInterval = () => 0, clearTimeout = () => {};
  const setTimeout = (fn, ms) => { timers.push({ at: vt + (ms || 0), fn }); return timers.length; };
  const innerWidth = 1280, innerHeight = 720, devicePixelRatio = 1, location = { protocol: "file:", host: "", hash: "", search: "" };
  const fetch = () => Promise.reject(new Error("offline")), WebSocket = function () {};
  ${body}
  return window.AG;
}
`;
writeFileSync(new URL("../src/tether-core.js", import.meta.url), out);
console.log("wrote src/tether-core.js", out.length);
